BusTicketSRC/BusTicketSRC/Areas/Admin/Controllers/TripsAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusTicketSRC.Models;

namespace BusTicketSRC.Areas.Admin.Controllers
{
    public class TripsAdminController : Controller
    {
        private BusTicketDB db = new BusTicketDB();

        // GET: Admin/TripsAdmin
        public ActionResult Index(string start_locationSearch = "", string end_locationSearch = "", string departure_daySearch = "")
        {
            using (BusTicketDB db = new BusTicketDB())
            {
                // Lấy danh sách unique sources và destinations từ database
                var start_locationOptions = db.Trips.Select(t => t.start_location).Distinct().ToList();
                var end_locationOptions = db.Trips.Select(t => t.end_location).Distinct().ToList();
                var departure_dayOptions = db.Trips.Select(t => t.departure_day).Distinct().ToList();

                // Gửi danh sách options lên View thông qua ViewBag
                ViewBag.Start_locationOptions = start_locationOptions;
                ViewBag.End_locationOptions = end_locationOptions;
                ViewBag.Departure_dayOptions = departure_dayOptions;

                // Lấy danh sách Trip từ database dựa trên điều kiện tìm kiếm
                List<Trip> trips = db.Trips
                    .Include(t => t.Bus) // Include Bus information
                    .Where(row =>
                        (string.IsNullOrEmpty(start_locationSearch) || row.start_location.ToLower().Contains(start_locationSearch.ToLower())) &&
                        (string.IsNullOrEmpty(end_locationSearch) || row.end_location.ToLower().Contains(end_locationSearch.ToLower())) &&
                        (string.IsNullOrEmpty(departure_daySearch) || row.departure_day.ToString().Contains(departure_daySearch)))
                    .ToList();


                // Gửi dữ liệu tìm kiếm và danh sách Trip lên View
                ViewBag.Start_locationSearch = start_locationSearch;
                ViewBag.End_locationSearch = end_locationSearch;
                ViewBag.Departure_daySearch = departure_daySearch;
                return View(trips);
            }
        }

        // GET: Admin/TripsAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // GET: Admin/TripsAdmin/Create
        public ActionResult Create()
        {
            ViewBag.bus_id = new SelectList(db.Buses, "bus_id", "bus_type");
            return View();
        }

        // POST: Admin/TripsAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "trip_id,bus_id,start_location,end_location,distance,departure_time,departure_day,Price,other_trip_details")] Trip trip)
        {
            // Kiểm tra nếu trip_id đã tồn tại
            if (db.Trips.Any(t => t.trip_id == trip.trip_id))
            {
                ModelState.AddModelError("trip_id", "Trip ID already exists. Please choose a different one.");
            }

            if (ModelState.IsValid)
            {
                db.Trips.Add(trip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.bus_id = new SelectList(db.Buses, "bus_id", "bus_type", trip.bus_id);
            return View(trip);
        }


        // GET: Admin/TripsAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            ViewBag.bus_id = new SelectList(db.Buses, "bus_id", "bus_type", trip.bus_id);
            return View(trip);
        }

        // POST: Admin/TripsAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "trip_id,bus_id,start_location,end_location,distance,departure_time,departure_day,Price,other_trip_details")] Trip trip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.bus_id = new SelectList(db.Buses, "bus_id", "bus_type", trip.bus_id);
            return View(trip);
        }

        // GET: Admin/TripsAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trip trip = db.Trips.Find(id);
            if (trip == null)
            {
                return HttpNotFound();
            }
            return View(trip);
        }

        // POST: Admin/TripsAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Trip trip = db.Trips.Find(id);
            db.Trips.Remove(trip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusTicketSRC/BusTicketSRC/Areas/Admin/Views/TripsAdmin/Create.cshtml
@model BusTicketSRC.Models.Trip

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Trip</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.bus_id, "Bus Type:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("bus_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.bus_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.start_location, "Start Location:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.start_location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.start_location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.end_location, "End Location:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.end_location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.end_location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.distance, "Distance:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.distance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.distance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.departure_day, "Departure Day:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.departure_day, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.departure_day, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.departure_time, "Departure Time:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.departure_time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.departure_time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price,"Price:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.other_trip_details, "Other Trip Details:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.other_trip_details, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.other_trip_details, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Check if flatpickr is defined
        if (typeof flatpickr === 'undefined') {
            console.error('Flatpickr is not defined. Check if the library is loaded correctly.');
            return;
        }

        // Enable flatpickr for departure_day
        flatpickr("#departure_day", {
            dateFormat: "d/m/Y", // Set the desired date format
            // Set the language to Vietnamese
        });

        // Enable flatpickr for departure_time
        flatpickr("#departure_time", {
            enableTime: true, // Enable time picker
            noCalendar: true, // Hide calendar
            dateFormat: "H:i", // Set the desired time format
            // Set the language to Vietnamese
        });
    });
</script>

BusTicketSRC/BusTicketSRC/Areas/Admin/Views/TripsAdmin/Delete.cshtml
@model BusTicketSRC.Models.Trip

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trip</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Bus Type:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bus.bus_type)
        </dd>

        <dt>
            Start Location:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.start_location)
        </dd>

        <dt>
            End Location:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.end_location)
        </dd>

        <dt>
            Distance:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.distance)
        </dd>

        <dt>
            Departure Time:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.departure_time)
        </dd>

        <dt>
            Departure Day:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.departure_day)
        </dd>

        <dt>
            Price:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            Other Trip Details:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.other_trip_details)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BusTicketSRC/BusTicketSRC/Areas/Admin/Views/TripsAdmin/Details.cshtml
@model BusTicketSRC.Models.Trip

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Trip</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Bus Type:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bus.bus_type)
        </dd>

        <dt>
            Start Location:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.start_location)
        </dd>

        <dt>
            End Location:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.end_location)
        </dd>

        <dt>
            Distance:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.distance)
        </dd>

        <dt>
            Departure Time:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.departure_time)
        </dd>

        <dt>
            Departure Day:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.departure_day)
        </dd>

        <dt>
            Price:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            Other Trip Details:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.other_trip_details)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.trip_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BusTicketSRC/BusTicketSRC/Areas/Admin/Views/TripsAdmin/Edit.cshtml
@model BusTicketSRC.Models.Trip

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Trip</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.trip_id)

    <div class="form-group">
        @Html.LabelFor(model => model.bus_id, "Bus Type:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("bus_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.bus_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.start_location, "Start Location:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.start_location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.start_location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.end_location, "End Location:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.end_location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.end_location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.distance,"Distance:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.distance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.distance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.departure_day, "Departure Day:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.departure_day, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.departure_day, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.departure_time, "Departure Time:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.departure_time, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.departure_time, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price,"Price:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.other_trip_details,"Other Trip Details:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.other_trip_details, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.other_trip_details, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Check if flatpickr is defined
        if (typeof flatpickr === 'undefined') {
            console.error('Flatpickr is not defined. Check if the library is loaded correctly.');
            return;
        }

        // Enable flatpickr for departure_day
        flatpickr("#departure_day", {
            dateFormat: "d/m/Y", // Set the desired date format
            // Set the language to Vietnamese
        });

        // Enable flatpickr for departure_time
        flatpickr("#departure_time", {
            enableTime: true, // Enable time picker
            noCalendar: true, // Hide calendar
            dateFormat: "H:i", // Set the desired time format
            // Set the language to Vietnamese
        });
    });
</script>

BusTicketSRC/BusTicketSRC/Areas/Admin/Views/TripsAdmin/Index.cshtml
@model IEnumerable<BusTicketSRC.Models.Trip>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<h2>Trip Management</h2>
<style>
    #searchForm {
        display: flex;
        align-items: center;
    }

    label {
        font-weight: bold;
        margin-right: 10px;
    }

    .select-container {
        position: relative;
    }

        .select-container select {
            width: 200px;
            padding: 10px;
            border: none;
            border-bottom: 2px solid #007bff;
            border-radius: 0;
            box-sizing: border-box;
            outline: none;
            transition: border-bottom-color 0.3s ease;
        }

            .select-container select:focus {
                border-bottom-color: #0056b3;
            }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: 2px solid #007bff;
        border-radius: 4px;
        padding: 10px 15px;
        cursor: pointer;
        transition: background-color 0.3s ease, border-color 0.3s ease;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

    .table-container {
        width: 80%;
        margin: 20px auto 0;
    }
</style>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<div class="form-container">
    <form id="searchForm" action="@Url.Action("Index", "TripsAdmin")" method="get" onsubmit="return validateSearchForm()">
        <div class="select-container">
            <label for="start_locationSearch">Source</label>
            <select class="form-control" id="start_locationSearch" name="start_locationSearch">
                <option value="">Select Source</option>
                @if (ViewBag.Start_locationOptions != null)
                {
                    foreach (var start_locationOption in ViewBag.Start_locationOptions)
                    {
                        <option value="@start_locationOption">@start_locationOption</option>
                    }
                }
            </select>
        </div>
        <div class="select-container">
            <label for="end_locationSearch">Destination</label>
            <select class="form-control" id="end_locationSearch" name="end_locationSearch">
                <option value="">Select Destination</option>
                @if (ViewBag.Start_locationOptions != null)
                {
                    foreach (var end_locationOption in ViewBag.End_locationOptions)
                    {
                        <option value="@end_locationOption">@end_locationOption</option>
                    }
                }
            </select>
        </div>
        <div class="select-container">
            <label for="departure_daySearch">Departure Time</label>
            <input type="text" class="form-control" id="departure_daySearch" name="departure_daySearch">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</div>
<script>
        flatpickr("#departure_daySearch", {
            dateFormat: "d/m/Y",  // Định dạng ngày/tháng/năm
        });

        function validateSearchForm() {
            var start_locationValue = document.getElementById("start_locationSearch").value.trim();
            var end_locationValue = document.getElementById("end_locationSearch").value.trim();
            var departure_dayValue = document.getElementById("departure_daySearch").value.trim();

            if (start_locationValue === "" && end_locationValue === "" && departure_dayValue === "") {
                alert("Please select values for source, destination, and departure day.");
                return false;
            }

            return true;
        }
</script>
<table class="table">
    <tr>
        <th>
            Code Trips
        </th>
        <th>
           Bus Type
        </th>
        <th>
            Start Location
        </th>
        <th>
            End Location
        </th>
        <th>
           Distance
        </th>
        <th>
            Departure Time
        </th>
        <th>
            Departure Day
        </th>
        <th>
            Price
        </th>
     
        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.trip_id)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bus.bus_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.start_location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.end_location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.distance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.departure_time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.departure_day)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)$
            </td>
         
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.trip_id, bus_id = item.bus_id, start_location = item.start_location, end_location = item.end_location, distance = item.distance, departure_time = item.departure_time, departure_day = item.departure_day, Price = item.Price, other_trip_details = item.other_trip_details })
                @Html.ActionLink("Details", "Details", new { id = item.trip_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.trip_id })
            </td>
        </tr>
    }

</table>